export const rebalancingVaultAbi = [
  { type: "receive", stateMutability: "payable" },
  // ═══ ERC-20 ═══
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  // ═══ Accounting ═══
  {
    type: "function",
    name: "grossAssets",
    inputs: [],
    outputs: [{ name: "totalUsdc8", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sharePriceUsdc8",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "circulatingShares",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "escrowedShares",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reservedHypeForClaims",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  // ═══ Rebalance state ═══
  {
    type: "function",
    name: "currentCycle",
    inputs: [],
    outputs: [
      { name: "cycleId", type: "uint256" },
      { name: "phase", type: "uint8" },
      { name: "startedAtL1Block", type: "uint64" },
      { name: "lastActionL1Block", type: "uint64" },
      { name: "deadline", type: "uint64" },
      { name: "expectedHypeDeltaWei", type: "int256" },
      { name: "expectedTokenDeltaWei", type: "int256" },
      { name: "expectedUsdcDeltaWei", type: "int256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentSettlement",
    inputs: [],
    outputs: [
      { name: "batchId", type: "uint256" },
      { name: "phase", type: "uint8" },
      { name: "lastActionL1Block", type: "uint64" },
      { name: "deadline", type: "uint64" },
      { name: "hypeEvmBefore", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextCycleId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  // ═══ Batch / Redeem ═══
  {
    type: "function",
    name: "currentBatchId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "processingBatchCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batches",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "totalEscrowedShares", type: "uint256" },
      { name: "claimedShares", type: "uint256" },
      { name: "totalHypeRecovered", type: "uint256" },
      { name: "remainingHypeForClaims", type: "uint256" },
      { name: "closedAtL1Block", type: "uint64" },
      { name: "settledAtL1Block", type: "uint64" },
      { name: "status", type: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "redeemRequests",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "user", type: "address" },
      { name: "shares", type: "uint256" },
      { name: "batchId", type: "uint256" },
      { name: "claimed", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserRedeemIds",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  // ═══ Config ═══
  {
    type: "function",
    name: "depositsEnabled",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxSingleDepositHype18",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "targetHypeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "targetTokenBps",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "targetUsdcBps",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "driftThresholdBps",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "slippageBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "counterpartToken",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  // ═══ Heartbeat & Emergency ═══
  {
    type: "function",
    name: "lastHeartbeat",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "heartbeatTimeout",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "emergencyMode",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isEmergency",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "recoveryComplete",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getL1BlockNumber",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
    stateMutability: "view",
  },
  // ═══ Deposit ═══
  {
    type: "function",
    name: "deposit",
    inputs: [],
    outputs: [{ name: "shares", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "previewDeposit",
    inputs: [{ name: "hypeEvmWei", type: "uint256" }],
    outputs: [{ name: "shares", type: "uint256" }],
    stateMutability: "view",
  },
  // ═══ Redeem ═══
  {
    type: "function",
    name: "requestRedeem",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ name: "redeemId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimBatch",
    inputs: [{ name: "redeemId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRecovery",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
